repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: trailing-whitespace
        exclude: "^build/"
      - id: check-yaml
      - id: check-added-large-files
        exclude: "^img/"
  - repo: https://github.com/jonasbb/pre-commit-latex-hooks
    rev: v1.4.4
    hooks:
      - id: american-eg-ie
        files: ".*\\.tex$"
      - id: cleveref-capitalization
      - id: consistent-spelling
        args:
            [
              "--emph=et al.",
              "--emph=a priori",
              "--emph=a posteriori",
              '--regex=naive=\bna(i|\\"i)ve',
            ]
      # - id: csquotes
      - id: ensure-labels-for-sections
        files: ".*\\.tex$"
        args:
            [
              # Only check that there is a \label{} but not the value
              "--ignore-label-content",
            ]
      - id: no-space-in-cite
      - id: tilde-cite
      - id: unique-labels
      - id: cleveref-instead-of-autoref
  - repo: https://github.com/cmhughes/latexindent.pl.git
    rev: V3.24.5
    hooks:
      - id: latexindent
        args: [-l, -m, -s]
