services:
  latex-ja:
    image: ghcr.io/nobu-g/latex-template-ja/latex-ja:latest
    # build: . # if you want to build the image locally
    volumes:  # host:container
      - ../:/workdir/paper
      # - ./.latexmkrc:/root/.latexmkrc
    tty: true
    environment:
      SHELL: "/bin/bash"
